### ISSUE TITLE
why to reset definitions on each evaluation?

### ISSUE THREAD

**Issue by mmatera** [JoseCarlosGarcia95/mathicsjupyternotebook#1]
https://github.com/JoseCarlosGarcia95/mathicsjupyternotebook/blob/8ba476f58d82c14ff690ca523548401ba8cc8a35/mathicsnotebook/kernel.py#L39
Hi Jose: it seems that each time you run a cell, you reset the definitions. I think that a better behavior would be to keep the same Definition object along all the life of the kernel. Something that could be useful is to generate a MathicsSession object when the kernel is created. This object package both definitions and an evaluation object.

**Comment by JoseCarlosGarcia95** [comment]
Hello,
Thanks for your recommendation, I'll take a look at it.

**Comment by JoseCarlosGarcia95** [comment]
Could you take a look to this PR?
Greetings
